### ISSUE TITLE
more diagnostics view unclear

### ISSUE THREAD

**Issue by mhandreae** [jgabry/SHINYstan#25]
I guess the Rhat and Eff n in the more diagnostics view show the values for the model parameters? But which is which is just not clear to me...? could they get names or could we flip coordinates and show them next to their names?

**Comment by jgabry** [comment]
We could show the names but that's not really the point of the plots on those pages. What I mean is that if you want Rhat values for particular parameters it makes more sense to just look up those parameters on the stats page rather than looking through the labels on a plot axis to figure out which one corresponds to the parameter you want. If there are many parameters it would just be so cluttered. 

But there's a compromise! 

These plots are intended to allow you to quickly tell if there are any parameters that have high Rhats or low effective sample sizes (or more precislely, a low ratio of effective samples to total samples). We can set a threshold level so that if the plots show that there are parameters that have these problems the names of these parameters are printed.
